apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-crypt-app
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: secrets
    repoURL: 'https://github.com/dharapvj/secrets-csi-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plain-secret-app
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: plain-secrets
    repoURL: 'https://github.com/dharapvj/secrets-csi-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubeseal-secrets
    repoURL: 'https://github.com/dharapvj/secrets-csi-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-app
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: secrets-operator
    repoURL: 'https://github.com/dharapvj/secrets-csi-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-csi-demo-app
  namespace: argocd  # MANDATORY
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: secrets-csi-demo-apps
    repoURL: 'https://github.com/dharapvj/secrets-csi-demo'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
