# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   annotations:
#     # eks.amazonaws.com/role-arn: arn:aws:iam::064814169464:role/my-sa.my-ns.sa.kopsdemo.k8s.local
#     eks.amazonaws.com/role-arn: arn:aws:iam::064814169464:role/pod-identity-webhook-test.default.sa.kopsdemo.k8s.local
#   name: pod-identity-webhook-test
#   namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::064814169464:role/sa-secrets-csi-demo.default.sa.kopsdemo.k8s.local
  name: sa-secrets-csi-demo
  namespace: default
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-provider-config
spec:
  provider: aws
  parameters:
    objects: |
      - objectType: "secretsmanager"
        objectName: "MySecret"
    region: ap-south-1