kind: Pod
apiVersion: v1
metadata:
  name: reader
  labels:
    app: reader-app
spec:
  containers:
  - name: reader
    image: docker.io/dharapvj/file-reader:1.0
    env:
      - name: MESSAGE
        value: "Welcome to Secrets-CSI Demo"
      - name: SECRET_PATH
        value: "/mnt/secrets-store"
      - name: SECRET_NAME
        value: "secrets-csi-demo"
    ports:
      - name: http-port
        containerPort: 3000
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
        nodePublishSecretRef:                       # Only required when using service principal mode
          name: secrets-store-creds                 # Only required when using service principal mode. The name of the Kubernetes secret that contains the service principal credentials to access keyvault.
---
apiVersion: v1
kind: Service
metadata:
  name: reader-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: reader-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reader-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /reader(/.*)
            pathType: Prefix
            backend:
              service:
                name: reader-svc
                port:
                  number: 3000
