apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 15s  ## <-- should be in hours in PRODUCTION.
  secretStoreRef:
    name: secretstore-sample ## <-- Name of secret Store
    kind: SecretStore
  target:
    name: secrets-operator-demo-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cds2023-secrets-operator   ## <-- AWS secret name