apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secrets-operator-demo-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cds2023-secrets-operator   #AWS secret name