apiVersion: v1
data:
  access-key: QUtJQVE2RlpaWFY0RlBGNVpBVUc=
  secret-access-key: ODMrN0pqbCsvNkVvVlk1YTdOblFJSnRUMWhHMnZLQzEySkJKSFp0RA==
kind: Secret
metadata:
  name: awssm-secret
  namespace: default
type: Opaque

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key