apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-secret-demo
  namespace: default
spec:
  encryptedData:
    secret-text.txt: AgCpsKPu41jAJB1w2WnlGv6VqiLn10Ob8ZvPKOLKH6HseR4gQVTU3LrsE1RC6dzJU/BxcTrfrKD3mY38dcq6dZnL2moWZG3DQiKb9+KhiGbZ6aIiOkn+8DiS9pNGf6n5QwA6E6Ot9tqzcMF4pcrYLmCigeXmDKW7yjzvugQEBEum/vaMedIVtSjofz33A53lVEvXoS3bgBJhmvknVBMnaM7G8mDRIGsgVtjLCYAK1h5V+JlT2u/zZottwU70zjKHLpvitXLLF8EmsXlLMZZlVtm0zhYHzSi5ljzI6y4+y0pV08+JTD3ZZqKMAnapzW8RdXiqFWW2UpsjBT1XTYj6Cda9dquhQtu7s8ajDiQLhunIDNN8crisgEEwOEqVMkvLN+T+FYH9n1fOMwF/wCYXB/YaSukm9QRMGt+3Enu8p6phfuUVtjTcCLl6spRdVGhUsnYfbBWyNOXVO2vhKJzt1h0eShjuGItiL02E+pgo3KuwKDfWhGGnKGef1pB6LDSVdqX5+JaBBLRcVDX3WP3Z2IGgARS3HwT9ZrtVZ72LdCnTZ8YqlUWRnZivQFpeTXmE607blNL0ruFNdqhLUY3AaAttMPYZJJe1ThcR1hQ1CUwkfLuuGRYQzAEbKO0jVm9SfBc7o+OlQgsW6OsxWgXRFa98M/DRgL/lAXP9I5eEZLgqPHq+BP8gT8o9YFCeHiLd5BgyEOyuvOJ+YoqO8ZSWfWEjq+i/rhg2wuhj54Xtmvkj3doAcLIZhBVq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sealed-secret-demo
      namespace: default

